export type InputType = "number" | "integer" | "percent" | "text";

export interface InputDefinition {
  row: number;
  cell: string;
  label: string;
  section: string;
  groupPath: string;
  groupTail: string[];
  tooltip: string;
  uiNote: string;
  sampleValue: string;
  type: InputType;
}

export const INPUT_DEFINITIONS: InputDefinition[] = [
  {
    row: 4,
    cell: "B4",
    label: "Your age",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Must be entered",
    uiNote: "",
    sampleValue: "48",
    type: "integer"
  },
  {
    row: 6,
    cell: "B6",
    label: "Current net annual income",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Net of tax, from employment or self-employment",
    uiNote: "",
    sampleValue: "80000",
    type: "number"
  },
  {
    row: 8,
    cell: "B8",
    label: "Total cash balances",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "current and savings accounts, bonds, term deposits",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 10,
    cell: "B10",
    label: "Stock market investments",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Current market value of equity portfolio",
    uiNote: "",
    sampleValue: "30000",
    type: "number"
  },
  {
    row: 12,
    cell: "B12",
    label: "Home current market value",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Leave blank if not a home owner",
    uiNote: "",
    sampleValue: "600000",
    type: "number"
  },
  {
    row: 15,
    cell: "B15",
    label: "Balance",
    section: "QUICK START",
    groupPath: "QUICK START > Home loan (mortgage)",
    groupTail: ["Home loan (mortgage)"],
    tooltip: "Leave blank if no mortgage",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 16,
    cell: "B16",
    label: "Interest rate",
    section: "QUICK START",
    groupPath: "QUICK START > Home loan (mortgage)",
    groupTail: ["Home loan (mortgage)"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 17,
    cell: "B17",
    label: "Monthly repayment",
    section: "QUICK START",
    groupPath: "QUICK START > Home loan (mortgage)",
    groupTail: ["Home loan (mortgage)"],
    tooltip: "",
    uiNote: "",
    sampleValue: "800",
    type: "number"
  },
  {
    row: 19,
    cell: "B19",
    label: "Statutory retirement age",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Age at which pension starts",
    uiNote: "",
    sampleValue: "65",
    type: "integer"
  },
  {
    row: 21,
    cell: "B21",
    label: "Annual pension at retirement",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Net annual state pension entitlement",
    uiNote: "",
    sampleValue: "16000",
    type: "number"
  },
  {
    row: 23,
    cell: "B23",
    label: "Housing rent",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "If not a home owner",
    uiNote: "show only if not a home owner (B12=\"\")",
    sampleValue: "",
    type: "number"
  },
  {
    row: 25,
    cell: "B25",
    label: "Annual living expenses",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 33,
    cell: "B33",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 1",
    groupTail: ["Dependents", "Dependent 1"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "John",
    type: "text"
  },
  {
    row: 34,
    cell: "B34",
    label: "Annual cost",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 1",
    groupTail: ["Dependents", "Dependent 1"],
    tooltip: "Food, education, healthcare,\netc.",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "2000",
    type: "number"
  },
  {
    row: 35,
    cell: "B35",
    label: "Years to support",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 1",
    groupTail: ["Dependents", "Dependent 1"],
    tooltip: "Years from now",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "3",
    type: "integer"
  },
  {
    row: 38,
    cell: "B38",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 2",
    groupTail: ["Dependents", "Dependent 2"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Jack",
    type: "text"
  },
  {
    row: 39,
    cell: "B39",
    label: "Annual cost",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 2",
    groupTail: ["Dependents", "Dependent 2"],
    tooltip: "Food, education, healthcare,\netc.",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "1000",
    type: "number"
  },
  {
    row: 40,
    cell: "B40",
    label: "Years to support",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 2",
    groupTail: ["Dependents", "Dependent 2"],
    tooltip: "Years from now",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "5",
    type: "integer"
  },
  {
    row: 43,
    cell: "B43",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 3",
    groupTail: ["Dependents", "Dependent 3"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Bill",
    type: "text"
  },
  {
    row: 44,
    cell: "B44",
    label: "Annual cost",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 3",
    groupTail: ["Dependents", "Dependent 3"],
    tooltip: "Food, education, healthcare,\netc.",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "4000",
    type: "number"
  },
  {
    row: 45,
    cell: "B45",
    label: "Years to support",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 3",
    groupTail: ["Dependents", "Dependent 3"],
    tooltip: "Years from now",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "2",
    type: "integer"
  },
  {
    row: 50,
    cell: "B50",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 1",
    groupTail: ["Investment Properties ", "Property 1"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Sliema",
    type: "text"
  },
  {
    row: 51,
    cell: "B51",
    label: "Market value",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 1",
    groupTail: ["Investment Properties ", "Property 1"],
    tooltip: "",
    uiNote: "Hide until user enters property name",
    sampleValue: "300000",
    type: "number"
  },
  {
    row: 52,
    cell: "B52",
    label: "Annual costs",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 1",
    groupTail: ["Investment Properties ", "Property 1"],
    tooltip: "Repairs, maintenance, etc.",
    uiNote: "Hide until user enters property name",
    sampleValue: "5000",
    type: "number"
  },
  {
    row: 55,
    cell: "B55",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 2",
    groupTail: ["Investment Properties ", "Property 2"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Gzira",
    type: "text"
  },
  {
    row: 56,
    cell: "B56",
    label: "Market value",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 2",
    groupTail: ["Investment Properties ", "Property 2"],
    tooltip: "",
    uiNote: "Hide until user enters property name",
    sampleValue: "150000",
    type: "number"
  },
  {
    row: 57,
    cell: "B57",
    label: "Annual costs",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 2",
    groupTail: ["Investment Properties ", "Property 2"],
    tooltip: "Repairs, maintenance, etc.",
    uiNote: "Hide until user enters property name",
    sampleValue: "2000",
    type: "number"
  },
  {
    row: 60,
    cell: "B60",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 3",
    groupTail: ["Investment Properties ", "Property 3"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Qormi",
    type: "text"
  },
  {
    row: 61,
    cell: "B61",
    label: "Market value",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 3",
    groupTail: ["Investment Properties ", "Property 3"],
    tooltip: "",
    uiNote: "Hide until user enters property name",
    sampleValue: "220000",
    type: "number"
  },
  {
    row: 62,
    cell: "B62",
    label: "Annual costs",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 3",
    groupTail: ["Investment Properties ", "Property 3"],
    tooltip: "Repairs, maintenance, etc.",
    uiNote: "Hide until user enters property name",
    sampleValue: "1200",
    type: "number"
  },
  {
    row: 66,
    cell: "B66",
    label: "Rental income: Sliema",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "net annual after all costs and tax",
    uiNote: "Show with property name only if name was entered",
    sampleValue: "12000",
    type: "number"
  },
  {
    row: 67,
    cell: "B67",
    label: "Rental income: Gzira",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "net annual after all costs and tax",
    uiNote: "Show with property name only if name was entered",
    sampleValue: "10000",
    type: "number"
  },
  {
    row: 68,
    cell: "B68",
    label: "Rental income: Qormi",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "net annual after all costs and tax",
    uiNote: "Show with property name only if name was entered",
    sampleValue: "8000",
    type: "number"
  },
  {
    row: 70,
    cell: "B70",
    label: "Other work income (net annual)",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "Part-time / consulting / side projects etc. Leave blank if none",
    uiNote: "",
    sampleValue: "2000",
    type: "number"
  },
  {
    row: 71,
    cell: "B71",
    label: "Continue other work until age",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "",
    uiNote: "Show only if other work income entered",
    sampleValue: "58",
    type: "integer"
  },
  {
    row: 75,
    cell: "B75",
    label: "Credit card balances",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans",
    groupTail: ["Other loans"],
    tooltip: "Assumed cleared in Year 1. Leave blank if none",
    uiNote: "",
    sampleValue: "1000",
    type: "number"
  },
  {
    row: 78,
    cell: "B78",
    label: "Balance",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Sliema Property",
    groupTail: ["Other loans", "Sliema Property"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 79,
    cell: "B79",
    label: "Interest rate",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Sliema Property",
    groupTail: ["Other loans", "Sliema Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 80,
    cell: "B80",
    label: "Monthly repayment",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Sliema Property",
    groupTail: ["Other loans", "Sliema Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "500",
    type: "number"
  },
  {
    row: 83,
    cell: "B83",
    label: "Balance",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Gzira Property",
    groupTail: ["Other loans", "Gzira Property"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "8500",
    type: "number"
  },
  {
    row: 84,
    cell: "B84",
    label: "Interest rate",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Gzira Property",
    groupTail: ["Other loans", "Gzira Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.02",
    type: "percent"
  },
  {
    row: 85,
    cell: "B85",
    label: "Monthly repayment",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Gzira Property",
    groupTail: ["Other loans", "Gzira Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "200",
    type: "number"
  },
  {
    row: 88,
    cell: "B88",
    label: "Balance",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Qormi Property",
    groupTail: ["Other loans", "Qormi Property"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "15000",
    type: "number"
  },
  {
    row: 89,
    cell: "B89",
    label: "Interest rate",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Qormi Property",
    groupTail: ["Other loans", "Qormi Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.05",
    type: "percent"
  },
  {
    row: 90,
    cell: "B90",
    label: "Monthly repayment",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Qormi Property",
    groupTail: ["Other loans", "Qormi Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "250",
    type: "number"
  },
  {
    row: 93,
    cell: "B93",
    label: "Balance",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Other loan",
    groupTail: ["Other loans", "Other loan"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "4000",
    type: "number"
  },
  {
    row: 94,
    cell: "B94",
    label: "Interest rate",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Other loan",
    groupTail: ["Other loans", "Other loan"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.06",
    type: "percent"
  },
  {
    row: 95,
    cell: "B95",
    label: "Monthly repayment",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Other loan",
    groupTail: ["Other loans", "Other loan"],
    tooltip: "",
    uiNote: "",
    sampleValue: "50",
    type: "number"
  },
  {
    row: 100,
    cell: "B100",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 1",
    groupTail: ["Major life income events", "Income Event 1"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Inheritance",
    type: "text"
  },
  {
    row: 101,
    cell: "B101",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 1",
    groupTail: ["Major life income events", "Income Event 1"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 102,
    cell: "B102",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 1",
    groupTail: ["Major life income events", "Income Event 1"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2035",
    type: "integer"
  },
  {
    row: 105,
    cell: "B105",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 2",
    groupTail: ["Major life income events", "Income Event 2"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Sell Painting",
    type: "text"
  },
  {
    row: 106,
    cell: "B106",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 2",
    groupTail: ["Major life income events", "Income Event 2"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "10000",
    type: "number"
  },
  {
    row: 107,
    cell: "B107",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 2",
    groupTail: ["Major life income events", "Income Event 2"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2029",
    type: "integer"
  },
  {
    row: 110,
    cell: "B110",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 3",
    groupTail: ["Major life income events", "Income Event 3"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Sell Jewels",
    type: "text"
  },
  {
    row: 111,
    cell: "B111",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 3",
    groupTail: ["Major life income events", "Income Event 3"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "5000",
    type: "number"
  },
  {
    row: 112,
    cell: "B112",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 3",
    groupTail: ["Major life income events", "Income Event 3"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2032",
    type: "integer"
  },
  {
    row: 117,
    cell: "B117",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 1",
    groupTail: ["Major life expense events", "Expense Event 1"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Wedding",
    type: "text"
  },
  {
    row: 118,
    cell: "B118",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 1",
    groupTail: ["Major life expense events", "Expense Event 1"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "40000",
    type: "number"
  },
  {
    row: 119,
    cell: "B119",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 1",
    groupTail: ["Major life expense events", "Expense Event 1"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2036",
    type: "integer"
  },
  {
    row: 122,
    cell: "B122",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 2",
    groupTail: ["Major life expense events", "Expense Event 2"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "New Car",
    type: "text"
  },
  {
    row: 123,
    cell: "B123",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 2",
    groupTail: ["Major life expense events", "Expense Event 2"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "35000",
    type: "number"
  },
  {
    row: 124,
    cell: "B124",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 2",
    groupTail: ["Major life expense events", "Expense Event 2"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2029",
    type: "integer"
  },
  {
    row: 127,
    cell: "B127",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 3",
    groupTail: ["Major life expense events", "Expense Event 3"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "New AC",
    type: "text"
  },
  {
    row: 128,
    cell: "B128",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 3",
    groupTail: ["Major life expense events", "Expense Event 3"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "15000",
    type: "number"
  },
  {
    row: 129,
    cell: "B129",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 3",
    groupTail: ["Major life expense events", "Expense Event 3"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2034",
    type: "integer"
  },
  {
    row: 134,
    cell: "B134",
    label: "Plan to live until age",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "",
    uiNote: "",
    sampleValue: "85",
    type: "integer"
  },
  {
    row: 137,
    cell: "B137",
    label: "from now to 65",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Spending adjustment (at today's euros)",
    groupTail: ["Spending adjustment (at today's euros)"],
    tooltip: "more / less than current",
    uiNote: "",
    sampleValue: "0",
    type: "percent"
  },
  {
    row: 138,
    cell: "B138",
    label: "from 66-75",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Spending adjustment (at today's euros)",
    groupTail: ["Spending adjustment (at today's euros)"],
    tooltip: "more / less than current",
    uiNote: "",
    sampleValue: "-0.1",
    type: "percent"
  },
  {
    row: 139,
    cell: "B139",
    label: "from age 76",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Spending adjustment (at today's euros)",
    groupTail: ["Spending adjustment (at today's euros)"],
    tooltip: "more / less than current",
    uiNote: "",
    sampleValue: "-0.2",
    type: "percent"
  },
  {
    row: 141,
    cell: "B141",
    label: "Other post-retirement income",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Other post-retirement income",
    groupTail: ["Other post-retirement income"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "12000",
    type: "number"
  },
  {
    row: 142,
    cell: "B142",
    label: "From age",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Other post-retirement income",
    groupTail: ["Other post-retirement income"],
    tooltip: "",
    uiNote: "Only show if value>0 entered in B141",
    sampleValue: "58",
    type: "integer"
  },
  {
    row: 143,
    cell: "B143",
    label: "To age",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Other post-retirement income",
    groupTail: ["Other post-retirement income"],
    tooltip: "",
    uiNote: "Only show if value>0 entered in B141",
    sampleValue: "69",
    type: "integer"
  },
  {
    row: 145,
    cell: "B145",
    label: "General inflatiion",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "",
    uiNote: "",
    sampleValue: "2.5000000000000001E-2",
    type: "percent"
  },
  {
    row: 147,
    cell: "B147",
    label: "Property annual appreciation",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "including inflation",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 149,
    cell: "B149",
    label: "Cash interest rate",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "including inflation",
    uiNote: "",
    sampleValue: "2.5000000000000001E-2",
    type: "percent"
  },
  {
    row: 151,
    cell: "B151",
    label: "Stock market return",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "including inflation",
    uiNote: "",
    sampleValue: "0.08",
    type: "percent"
  },
  {
    row: 153,
    cell: "B153",
    label: "Salary annual growth rate",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "including inflation",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 155,
    cell: "B155",
    label: "Rental income annual increase",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 157,
    cell: "B157",
    label: "Pension reduction per year early",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "reduction in pension for each year retired early",
    uiNote: "",
    sampleValue: "300",
    type: "number"
  },
  {
    row: 159,
    cell: "B159",
    label: "Cash buffer at any time",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "emergency reserve",
    uiNote: "",
    sampleValue: "40000",
    type: "number"
  },
  {
    row: 161,
    cell: "B161",
    label: "Stock market selling costs",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "tax, broker and other fees",
    uiNote: "",
    sampleValue: "0.05",
    type: "percent"
  },
  {
    row: 163,
    cell: "B163",
    label: "Property disposal costs",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "agency, tax, legal fees",
    uiNote: "",
    sampleValue: "0.15",
    type: "percent"
  },
  {
    row: 166,
    cell: "B166",
    label: "Sliema",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Property liquidation order",
    groupTail: ["Property liquidation order"],
    tooltip: "0 = would never sell",
    uiNote: "",
    sampleValue: "3",
    type: "integer"
  },
  {
    row: 167,
    cell: "B167",
    label: "Gzira",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Property liquidation order",
    groupTail: ["Property liquidation order"],
    tooltip: "",
    uiNote: "",
    sampleValue: "1",
    type: "integer"
  },
  {
    row: 168,
    cell: "B168",
    label: "Qormi",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Property liquidation order",
    groupTail: ["Property liquidation order"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2",
    type: "integer"
  },
];
