import { FIELD_ID_TO_CELL, FieldId, InputCell } from "../model/fieldRegistry";

export type InputType = "number" | "integer" | "percent" | "text";

export interface InputDefinition {
  row: number;
  fieldId: FieldId;
  cell: InputCell;
  label: string;
  section: string;
  groupPath: string;
  groupTail: string[];
  tooltip: string;
  uiNote: string;
  sampleValue: string;
  type: InputType;
}

type AuthoredInputDefinition = Omit<InputDefinition, "cell">;

const AUTHORED_INPUT_DEFINITIONS: AuthoredInputDefinition[] = [
  {
    row: 4,
    fieldId: "profile.currentAge",
    label: "Your age",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Must be entered",
    uiNote: "",
    sampleValue: "48",
    type: "integer"
  },
  {
    row: 6,
    fieldId: "income.employment.netAnnual",
    label: "Current net annual income",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Net of tax, from employment or self-employment",
    uiNote: "",
    sampleValue: "80000",
    type: "number"
  },
  {
    row: 8,
    fieldId: "assets.cash.totalBalance",
    label: "Total cash balances",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Current and savings accounts, bonds, and term deposits",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 10,
    fieldId: "assets.equities.marketValue",
    label: "Stock market investments",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Current market value of equity portfolio",
    uiNote: "",
    sampleValue: "30000",
    type: "number"
  },
  {
    row: 12,
    fieldId: "housing.01Residence.marketValue",
    label: "Home current market value",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Leave blank if not a home owner",
    uiNote: "",
    sampleValue: "600000",
    type: "number"
  },
  {
    row: 15,
    fieldId: "housing.01Residence.mortgage.balance",
    label: "Balance",
    section: "QUICK START",
    groupPath: "QUICK START > Home loan (mortgage)",
    groupTail: ["Home loan (mortgage)"],
    tooltip: "Leave blank if no mortgage",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 16,
    fieldId: "housing.01Residence.mortgage.interestRateAnnual",
    label: "Interest rate",
    section: "QUICK START",
    groupPath: "QUICK START > Home loan (mortgage)",
    groupTail: ["Home loan (mortgage)"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 17,
    fieldId: "housing.01Residence.mortgage.monthlyRepayment",
    label: "Monthly repayment",
    section: "QUICK START",
    groupPath: "QUICK START > Home loan (mortgage)",
    groupTail: ["Home loan (mortgage)"],
    tooltip: "",
    uiNote: "",
    sampleValue: "800",
    type: "number"
  },
  {
    row: 19,
    fieldId: "retirement.statutoryAge",
    label: "Statutory retirement age",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Age at which pension starts",
    uiNote: "",
    sampleValue: "65",
    type: "integer"
  },
  {
    row: 21,
    fieldId: "retirement.statePension.netAnnualAtStart",
    label: "Annual pension at retirement",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "Net annual state pension entitlement",
    uiNote: "",
    sampleValue: "16000",
    type: "number"
  },
  {
    row: 23,
    fieldId: "housing.rentAnnual",
    label: "Housing rent",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "If not a home owner",
    uiNote: "show only if not a home owner (B12=\"\")",
    sampleValue: "",
    type: "number"
  },
  {
    row: 25,
    fieldId: "spending.livingExpenses.annual",
    label: "Annual living expenses",
    section: "QUICK START",
    groupPath: "QUICK START",
    groupTail: [],
    tooltip: "",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 33,
    fieldId: "dependents.01.displayName",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 1",
    groupTail: ["Dependents", "Dependent 1"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "John",
    type: "text"
  },
  {
    row: 34,
    fieldId: "dependents.01.annualCost",
    label: "Annual cost",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 1",
    groupTail: ["Dependents", "Dependent 1"],
    tooltip: "Food, education, healthcare,\netc.",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "2000",
    type: "number"
  },
  {
    row: 35,
    fieldId: "dependents.01.supportYearsRemaining",
    label: "Years to support",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 1",
    groupTail: ["Dependents", "Dependent 1"],
    tooltip: "Years from now",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "3",
    type: "integer"
  },
  {
    row: 38,
    fieldId: "dependents.02.displayName",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 2",
    groupTail: ["Dependents", "Dependent 2"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Jack",
    type: "text"
  },
  {
    row: 39,
    fieldId: "dependents.02.annualCost",
    label: "Annual cost",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 2",
    groupTail: ["Dependents", "Dependent 2"],
    tooltip: "Food, education, healthcare,\netc.",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "1000",
    type: "number"
  },
  {
    row: 40,
    fieldId: "dependents.02.supportYearsRemaining",
    label: "Years to support",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 2",
    groupTail: ["Dependents", "Dependent 2"],
    tooltip: "Years from now",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "5",
    type: "integer"
  },
  {
    row: 43,
    fieldId: "dependents.03.displayName",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 3",
    groupTail: ["Dependents", "Dependent 3"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Bill",
    type: "text"
  },
  {
    row: 44,
    fieldId: "dependents.03.annualCost",
    label: "Annual cost",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 3",
    groupTail: ["Dependents", "Dependent 3"],
    tooltip: "Food, education, healthcare,\netc.",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "4000",
    type: "number"
  },
  {
    row: 45,
    fieldId: "dependents.03.supportYearsRemaining",
    label: "Years to support",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Dependents > Dependent 3",
    groupTail: ["Dependents", "Dependent 3"],
    tooltip: "Years from now",
    uiNote: "Hide until user enters dependent name",
    sampleValue: "2",
    type: "integer"
  },
  {
    row: 50,
    fieldId: "properties.01.displayName",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 1",
    groupTail: ["Investment Properties ", "Property 1"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Sliema",
    type: "text"
  },
  {
    row: 51,
    fieldId: "properties.01.marketValue",
    label: "Market value",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 1",
    groupTail: ["Investment Properties ", "Property 1"],
    tooltip: "",
    uiNote: "Hide until user enters property name",
    sampleValue: "300000",
    type: "number"
  },
  {
    row: 52,
    fieldId: "properties.01.annualOperatingCost",
    label: "Annual costs",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 1",
    groupTail: ["Investment Properties ", "Property 1"],
    tooltip: "Repairs, maintenance, etc.",
    uiNote: "Hide until user enters property name",
    sampleValue: "5000",
    type: "number"
  },
  {
    row: 55,
    fieldId: "properties.02.displayName",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 2",
    groupTail: ["Investment Properties ", "Property 2"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Gzira",
    type: "text"
  },
  {
    row: 56,
    fieldId: "properties.02.marketValue",
    label: "Market value",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 2",
    groupTail: ["Investment Properties ", "Property 2"],
    tooltip: "",
    uiNote: "Hide until user enters property name",
    sampleValue: "150000",
    type: "number"
  },
  {
    row: 57,
    fieldId: "properties.02.annualOperatingCost",
    label: "Annual costs",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 2",
    groupTail: ["Investment Properties ", "Property 2"],
    tooltip: "Repairs, maintenance, etc.",
    uiNote: "Hide until user enters property name",
    sampleValue: "2000",
    type: "number"
  },
  {
    row: 60,
    fieldId: "properties.03.displayName",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 3",
    groupTail: ["Investment Properties ", "Property 3"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Qormi",
    type: "text"
  },
  {
    row: 61,
    fieldId: "properties.03.marketValue",
    label: "Market value",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 3",
    groupTail: ["Investment Properties ", "Property 3"],
    tooltip: "",
    uiNote: "Hide until user enters property name",
    sampleValue: "220000",
    type: "number"
  },
  {
    row: 62,
    fieldId: "properties.03.annualOperatingCost",
    label: "Annual costs",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Investment Properties  > Property 3",
    groupTail: ["Investment Properties ", "Property 3"],
    tooltip: "Repairs, maintenance, etc.",
    uiNote: "Hide until user enters property name",
    sampleValue: "1200",
    type: "number"
  },
  {
    row: 66,
    fieldId: "properties.01.rentalIncomeNetAnnual",
    label: "Rental income: Sliema",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "Net annual after all costs and tax",
    uiNote: "Show with property name only if name was entered",
    sampleValue: "12000",
    type: "number"
  },
  {
    row: 67,
    fieldId: "properties.02.rentalIncomeNetAnnual",
    label: "Rental income: Gzira",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "Net annual after all costs and tax",
    uiNote: "Show with property name only if name was entered",
    sampleValue: "10000",
    type: "number"
  },
  {
    row: 68,
    fieldId: "properties.03.rentalIncomeNetAnnual",
    label: "Rental income: Qormi",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "Net annual after all costs and tax",
    uiNote: "Show with property name only if name was entered",
    sampleValue: "8000",
    type: "number"
  },
  {
    row: 70,
    fieldId: "income.otherWork.netAnnual",
    label: "Other work income (net annual)",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "Part-time / consulting / side projects etc. Leave blank if none",
    uiNote: "",
    sampleValue: "2000",
    type: "number"
  },
  {
    row: 71,
    fieldId: "income.otherWork.endAge",
    label: "Continue other work until age",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other income",
    groupTail: ["Other income"],
    tooltip: "",
    uiNote: "Show only if other work income entered",
    sampleValue: "58",
    type: "integer"
  },
  {
    row: 75,
    fieldId: "debts.creditCards.balance",
    label: "Credit card balances",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans",
    groupTail: ["Other loans"],
    tooltip: "Assumed cleared in Year 1. Leave blank if none",
    uiNote: "",
    sampleValue: "1000",
    type: "number"
  },
  {
    row: 78,
    fieldId: "properties.01.loan.balance",
    label: "Balance",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Sliema Property",
    groupTail: ["Other loans", "Sliema Property"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 79,
    fieldId: "properties.01.loan.interestRateAnnual",
    label: "Interest rate",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Sliema Property",
    groupTail: ["Other loans", "Sliema Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 80,
    fieldId: "properties.01.loan.monthlyRepayment",
    label: "Monthly repayment",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Sliema Property",
    groupTail: ["Other loans", "Sliema Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "500",
    type: "number"
  },
  {
    row: 83,
    fieldId: "properties.02.loan.balance",
    label: "Balance",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Gzira Property",
    groupTail: ["Other loans", "Gzira Property"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "8500",
    type: "number"
  },
  {
    row: 84,
    fieldId: "properties.02.loan.interestRateAnnual",
    label: "Interest rate",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Gzira Property",
    groupTail: ["Other loans", "Gzira Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.02",
    type: "percent"
  },
  {
    row: 85,
    fieldId: "properties.02.loan.monthlyRepayment",
    label: "Monthly repayment",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Gzira Property",
    groupTail: ["Other loans", "Gzira Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "200",
    type: "number"
  },
  {
    row: 88,
    fieldId: "properties.03.loan.balance",
    label: "Balance",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Qormi Property",
    groupTail: ["Other loans", "Qormi Property"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "15000",
    type: "number"
  },
  {
    row: 89,
    fieldId: "properties.03.loan.interestRateAnnual",
    label: "Interest rate",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Qormi Property",
    groupTail: ["Other loans", "Qormi Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.05",
    type: "percent"
  },
  {
    row: 90,
    fieldId: "properties.03.loan.monthlyRepayment",
    label: "Monthly repayment",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Qormi Property",
    groupTail: ["Other loans", "Qormi Property"],
    tooltip: "",
    uiNote: "",
    sampleValue: "250",
    type: "number"
  },
  {
    row: 93,
    fieldId: "debts.other.balance",
    label: "Balance",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Other loan",
    groupTail: ["Other loans", "Other loan"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "4000",
    type: "number"
  },
  {
    row: 94,
    fieldId: "debts.other.interestRateAnnual",
    label: "Interest rate",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Other loan",
    groupTail: ["Other loans", "Other loan"],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.06",
    type: "percent"
  },
  {
    row: 95,
    fieldId: "debts.other.monthlyRepayment",
    label: "Monthly repayment",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Other loans > Other loan",
    groupTail: ["Other loans", "Other loan"],
    tooltip: "",
    uiNote: "",
    sampleValue: "50",
    type: "number"
  },
  {
    row: 100,
    fieldId: "cashflowEvents.income.01.name",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 1",
    groupTail: ["Major life income events", "Income Event 1"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Inheritance",
    type: "text"
  },
  {
    row: 101,
    fieldId: "cashflowEvents.income.01.amount",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 1",
    groupTail: ["Major life income events", "Income Event 1"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "50000",
    type: "number"
  },
  {
    row: 102,
    fieldId: "cashflowEvents.income.01.year",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 1",
    groupTail: ["Major life income events", "Income Event 1"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2035",
    type: "integer"
  },
  {
    row: 105,
    fieldId: "cashflowEvents.income.02.name",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 2",
    groupTail: ["Major life income events", "Income Event 2"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Sell Painting",
    type: "text"
  },
  {
    row: 106,
    fieldId: "cashflowEvents.income.02.amount",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 2",
    groupTail: ["Major life income events", "Income Event 2"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "10000",
    type: "number"
  },
  {
    row: 107,
    fieldId: "cashflowEvents.income.02.year",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 2",
    groupTail: ["Major life income events", "Income Event 2"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2029",
    type: "integer"
  },
  {
    row: 110,
    fieldId: "cashflowEvents.income.03.name",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 3",
    groupTail: ["Major life income events", "Income Event 3"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Sell Jewels",
    type: "text"
  },
  {
    row: 111,
    fieldId: "cashflowEvents.income.03.amount",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 3",
    groupTail: ["Major life income events", "Income Event 3"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "5000",
    type: "number"
  },
  {
    row: 112,
    fieldId: "cashflowEvents.income.03.year",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life income events > Income Event 3",
    groupTail: ["Major life income events", "Income Event 3"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2032",
    type: "integer"
  },
  {
    row: 117,
    fieldId: "cashflowEvents.expense.01.name",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 1",
    groupTail: ["Major life expense events", "Expense Event 1"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "Wedding",
    type: "text"
  },
  {
    row: 118,
    fieldId: "cashflowEvents.expense.01.amount",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 1",
    groupTail: ["Major life expense events", "Expense Event 1"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "40000",
    type: "number"
  },
  {
    row: 119,
    fieldId: "cashflowEvents.expense.01.year",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 1",
    groupTail: ["Major life expense events", "Expense Event 1"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2036",
    type: "integer"
  },
  {
    row: 122,
    fieldId: "cashflowEvents.expense.02.name",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 2",
    groupTail: ["Major life expense events", "Expense Event 2"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "New Car",
    type: "text"
  },
  {
    row: 123,
    fieldId: "cashflowEvents.expense.02.amount",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 2",
    groupTail: ["Major life expense events", "Expense Event 2"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "35000",
    type: "number"
  },
  {
    row: 124,
    fieldId: "cashflowEvents.expense.02.year",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 2",
    groupTail: ["Major life expense events", "Expense Event 2"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2029",
    type: "integer"
  },
  {
    row: 127,
    fieldId: "cashflowEvents.expense.03.name",
    label: "Name",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 3",
    groupTail: ["Major life expense events", "Expense Event 3"],
    tooltip: "Leave blank if none",
    uiNote: "",
    sampleValue: "New AC",
    type: "text"
  },
  {
    row: 128,
    fieldId: "cashflowEvents.expense.03.amount",
    label: "Amount",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 3",
    groupTail: ["Major life expense events", "Expense Event 3"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "15000",
    type: "number"
  },
  {
    row: 129,
    fieldId: "cashflowEvents.expense.03.year",
    label: "Year",
    section: "DEEPER DIVE",
    groupPath: "DEEPER DIVE > Major life expense events > Expense Event 3",
    groupTail: ["Major life expense events", "Expense Event 3"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2034",
    type: "integer"
  },
  {
    row: 134,
    fieldId: "planning.lifeExpectancyAge",
    label: "Plan to live until age",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "",
    uiNote: "",
    sampleValue: "85",
    type: "integer"
  },
  {
    row: 137,
    fieldId: "spending.adjustments.pre65.deltaRate",
    label: "From now to 65",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Spending adjustment (at today's euros)",
    groupTail: ["Spending adjustment (at today's euros)"],
    tooltip: "More / less than current",
    uiNote: "",
    sampleValue: "0",
    type: "percent"
  },
  {
    row: 138,
    fieldId: "spending.adjustments.age66To75.deltaRate",
    label: "From 66 to 75",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Spending adjustment (at today's euros)",
    groupTail: ["Spending adjustment (at today's euros)"],
    tooltip: "More / less than current",
    uiNote: "",
    sampleValue: "-0.1",
    type: "percent"
  },
  {
    row: 139,
    fieldId: "spending.adjustments.age76Plus.deltaRate",
    label: "From age 76",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Spending adjustment (at today's euros)",
    groupTail: ["Spending adjustment (at today's euros)"],
    tooltip: "More / less than current",
    uiNote: "",
    sampleValue: "-0.2",
    type: "percent"
  },
  {
    row: 141,
    fieldId: "income.postRetirementSupplement.annual",
    label: "Other post-retirement income",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Other post-retirement income",
    groupTail: ["Other post-retirement income"],
    tooltip: "Enter 0 or leave blank if none",
    uiNote: "",
    sampleValue: "12000",
    type: "number"
  },
  {
    row: 142,
    fieldId: "income.postRetirementSupplement.startAge",
    label: "From age",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Other post-retirement income",
    groupTail: ["Other post-retirement income"],
    tooltip: "",
    uiNote: "Only show if value>0 entered in B141",
    sampleValue: "58",
    type: "integer"
  },
  {
    row: 143,
    fieldId: "income.postRetirementSupplement.endAge",
    label: "To age",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Other post-retirement income",
    groupTail: ["Other post-retirement income"],
    tooltip: "",
    uiNote: "Only show if value>0 entered in B141",
    sampleValue: "69",
    type: "integer"
  },
  {
    row: 145,
    fieldId: "assumptions.generalInflationRateAnnual",
    label: "General inflation",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "",
    uiNote: "",
    sampleValue: "2.5000000000000001E-2",
    type: "percent"
  },
  {
    row: 147,
    fieldId: "assumptions.propertyAppreciationRateAnnual",
    label: "Property annual appreciation",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "Including inflation",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 149,
    fieldId: "assumptions.cashYieldRateAnnual",
    label: "Cash interest rate",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "Including inflation",
    uiNote: "",
    sampleValue: "2.5000000000000001E-2",
    type: "percent"
  },
  {
    row: 151,
    fieldId: "assumptions.equityReturnRateAnnual",
    label: "Stock market return",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "Including inflation",
    uiNote: "",
    sampleValue: "0.08",
    type: "percent"
  },
  {
    row: 153,
    fieldId: "assumptions.salaryGrowthRateAnnual",
    label: "Salary annual growth rate",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "Including inflation",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 155,
    fieldId: "assumptions.rentalIncomeGrowthRateAnnual",
    label: "Rental income annual increase",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "",
    uiNote: "",
    sampleValue: "0.03",
    type: "percent"
  },
  {
    row: 157,
    fieldId: "retirement.earlyPensionReductionPerYear",
    label: "Pension reduction per year early",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "Reduction in pension for each year retired early",
    uiNote: "",
    sampleValue: "300",
    type: "number"
  },
  {
    row: 159,
    fieldId: "liquidity.minimumCashBuffer",
    label: "Cash buffer at any time",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "Emergency reserve",
    uiNote: "",
    sampleValue: "40000",
    type: "number"
  },
  {
    row: 161,
    fieldId: "liquidation.stockSellingCostRate",
    label: "Stock market selling costs",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "Tax, broker, and other fees",
    uiNote: "",
    sampleValue: "0.05",
    type: "percent"
  },
  {
    row: 163,
    fieldId: "liquidation.propertyDisposalCostRate",
    label: "Property disposal costs",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS",
    groupTail: [],
    tooltip: "Agency, tax, and legal fees",
    uiNote: "",
    sampleValue: "0.15",
    type: "percent"
  },
  {
    row: 166,
    fieldId: "properties.01.liquidationPriority",
    label: "Sliema",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Property liquidation order",
    groupTail: ["Property liquidation order"],
    tooltip: "0 = would never sell",
    uiNote: "",
    sampleValue: "3",
    type: "integer"
  },
  {
    row: 167,
    fieldId: "properties.02.liquidationPriority",
    label: "Gzira",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Property liquidation order",
    groupTail: ["Property liquidation order"],
    tooltip: "",
    uiNote: "",
    sampleValue: "1",
    type: "integer"
  },
  {
    row: 168,
    fieldId: "properties.03.liquidationPriority",
    label: "Qormi",
    section: "FINER DETAILS",
    groupPath: "FINER DETAILS > Property liquidation order",
    groupTail: ["Property liquidation order"],
    tooltip: "",
    uiNote: "",
    sampleValue: "2",
    type: "integer"
  }
];

export const INPUT_DEFINITIONS: InputDefinition[] = AUTHORED_INPUT_DEFINITIONS.map((def) => ({
  ...def,
  cell: FIELD_ID_TO_CELL[def.fieldId]
}));
