export const CELL_TO_FIELD_ID = {
  B4: "profile.currentAge",
  B6: "income.employment.netAnnual",
  B8: "assets.cash.totalBalance",
  B10: "assets.equities.marketValue",
  B12: "housing.01Residence.marketValue",
  B15: "housing.01Residence.mortgage.balance",
  B16: "housing.01Residence.mortgage.interestRateAnnual",
  B17: "housing.01Residence.mortgage.monthlyRepayment",
  B19: "retirement.statutoryAge",
  B21: "retirement.statePension.netAnnualAtStart",
  B23: "housing.rentAnnual",
  B25: "spending.livingExpenses.annual",
  B33: "dependents.01.displayName",
  B34: "dependents.01.annualCost",
  B35: "dependents.01.supportYearsRemaining",
  B38: "dependents.02.displayName",
  B39: "dependents.02.annualCost",
  B40: "dependents.02.supportYearsRemaining",
  B43: "dependents.03.displayName",
  B44: "dependents.03.annualCost",
  B45: "dependents.03.supportYearsRemaining",
  B48: "dependents.04.displayName",
  B49: "dependents.04.annualCost",
  B50: "dependents.04.supportYearsRemaining",
  B53: "dependents.05.displayName",
  B54: "dependents.05.annualCost",
  B55: "dependents.05.supportYearsRemaining",
  B60: "properties.01.displayName",
  B61: "properties.01.marketValue",
  B62: "properties.01.annualOperatingCost",
  B65: "properties.02.displayName",
  B66: "properties.02.marketValue",
  B67: "properties.02.annualOperatingCost",
  B70: "properties.03.displayName",
  B71: "properties.03.marketValue",
  B72: "properties.03.annualOperatingCost",
  B75: "properties.04.displayName",
  B76: "properties.04.marketValue",
  B77: "properties.04.annualOperatingCost",
  B80: "properties.05.displayName",
  B81: "properties.05.marketValue",
  B82: "properties.05.annualOperatingCost",
  B86: "properties.01.rentalIncomeNetAnnual",
  B87: "properties.02.rentalIncomeNetAnnual",
  B88: "properties.03.rentalIncomeNetAnnual",
  B89: "properties.04.rentalIncomeNetAnnual",
  B90: "properties.05.rentalIncomeNetAnnual",
  B92: "income.otherWork.netAnnual",
  B93: "income.otherWork.endAge",
  B97: "debts.creditCards.balance",
  B100: "properties.01.loan.balance",
  B101: "properties.01.loan.interestRateAnnual",
  B102: "properties.01.loan.monthlyRepayment",
  B105: "properties.02.loan.balance",
  B106: "properties.02.loan.interestRateAnnual",
  B107: "properties.02.loan.monthlyRepayment",
  B110: "properties.03.loan.balance",
  B111: "properties.03.loan.interestRateAnnual",
  B112: "properties.03.loan.monthlyRepayment",
  B115: "properties.04.loan.balance",
  B116: "properties.04.loan.interestRateAnnual",
  B117: "properties.04.loan.monthlyRepayment",
  B120: "properties.05.loan.balance",
  B121: "properties.05.loan.interestRateAnnual",
  B122: "properties.05.loan.monthlyRepayment",
  B125: "debts.other.balance",
  B126: "debts.other.interestRateAnnual",
  B127: "debts.other.monthlyRepayment",
  B132: "cashflowEvents.income.01.name",
  B133: "cashflowEvents.income.01.amount",
  B134: "cashflowEvents.income.01.year",
  B137: "cashflowEvents.income.02.name",
  B138: "cashflowEvents.income.02.amount",
  B139: "cashflowEvents.income.02.year",
  B142: "cashflowEvents.income.03.name",
  B143: "cashflowEvents.income.03.amount",
  B144: "cashflowEvents.income.03.year",
  B149: "cashflowEvents.expense.01.name",
  B150: "cashflowEvents.expense.01.amount",
  B151: "cashflowEvents.expense.01.year",
  B154: "cashflowEvents.expense.02.name",
  B155: "cashflowEvents.expense.02.amount",
  B156: "cashflowEvents.expense.02.year",
  B159: "cashflowEvents.expense.03.name",
  B160: "cashflowEvents.expense.03.amount",
  B161: "cashflowEvents.expense.03.year",
  B166: "planning.lifeExpectancyAge",
  B169: "spending.adjustments.pre65.deltaRate",
  B170: "spending.adjustments.age66To75.deltaRate",
  B171: "spending.adjustments.age76Plus.deltaRate",
  B173: "income.postRetirementSupplement.annual",
  B174: "income.postRetirementSupplement.startAge",
  B175: "income.postRetirementSupplement.endAge",
  B177: "assumptions.generalInflationRateAnnual",
  B179: "assumptions.propertyAppreciationRateAnnual",
  B181: "assumptions.cashYieldRateAnnual",
  B183: "assumptions.equityReturnRateAnnual",
  B185: "assumptions.salaryGrowthRateAnnual",
  B187: "assumptions.rentalIncomeGrowthRateAnnual",
  B189: "retirement.earlyPensionReductionPerYear",
  B191: "liquidity.minimumCashBuffer",
  B193: "planning.legacyAmount",
  B195: "liquidation.stockSellingCostRate",
  B197: "liquidation.propertyDisposalCostRate",
  B200: "properties.01.liquidationPriority",
  B201: "properties.02.liquidationPriority",
  B202: "properties.03.liquidationPriority",
  B203: "properties.04.liquidationPriority",
  B204: "properties.05.liquidationPriority"
} as const;

export type InputCell = keyof typeof CELL_TO_FIELD_ID;
export type FieldId = (typeof CELL_TO_FIELD_ID)[InputCell];

export const FIELD_ID_TO_CELL: Record<FieldId, InputCell> = Object.fromEntries(
  Object.entries(CELL_TO_FIELD_ID).map(([cell, fieldId]) => [fieldId, cell])
) as Record<FieldId, InputCell>;

export const ALL_INPUT_CELLS = Object.keys(CELL_TO_FIELD_ID) as InputCell[];
export const ALL_FIELD_IDS = Object.values(CELL_TO_FIELD_ID) as FieldId[];
