export const CELL_TO_FIELD_ID = {
  B4: "profile.currentAge",
  B6: "income.employment.netAnnual",
  B8: "assets.cash.totalBalance",
  B10: "assets.equities.marketValue",
  B12: "housing.primaryResidence.marketValue",
  B15: "housing.primaryResidence.mortgage.balance",
  B16: "housing.primaryResidence.mortgage.interestRateAnnual",
  B17: "housing.primaryResidence.mortgage.monthlyRepayment",
  B19: "retirement.statutoryAge",
  B21: "retirement.statePension.netAnnualAtStart",
  B23: "housing.rentAnnual",
  B25: "spending.livingExpenses.annual",
  B33: "dependents.primary.displayName",
  B34: "dependents.primary.annualCost",
  B35: "dependents.primary.supportYearsRemaining",
  B38: "dependents.secondary.displayName",
  B39: "dependents.secondary.annualCost",
  B40: "dependents.secondary.supportYearsRemaining",
  B43: "dependents.tertiary.displayName",
  B44: "dependents.tertiary.annualCost",
  B45: "dependents.tertiary.supportYearsRemaining",
  B50: "properties.primary.displayName",
  B51: "properties.primary.marketValue",
  B52: "properties.primary.annualOperatingCost",
  B55: "properties.secondary.displayName",
  B56: "properties.secondary.marketValue",
  B57: "properties.secondary.annualOperatingCost",
  B60: "properties.tertiary.displayName",
  B61: "properties.tertiary.marketValue",
  B62: "properties.tertiary.annualOperatingCost",
  B66: "properties.primary.rentalIncomeNetAnnual",
  B67: "properties.secondary.rentalIncomeNetAnnual",
  B68: "properties.tertiary.rentalIncomeNetAnnual",
  B70: "income.otherWork.netAnnual",
  B71: "income.otherWork.endAge",
  B75: "debts.creditCards.balance",
  B78: "properties.primary.loan.balance",
  B79: "properties.primary.loan.interestRateAnnual",
  B80: "properties.primary.loan.monthlyRepayment",
  B83: "properties.secondary.loan.balance",
  B84: "properties.secondary.loan.interestRateAnnual",
  B85: "properties.secondary.loan.monthlyRepayment",
  B88: "properties.tertiary.loan.balance",
  B89: "properties.tertiary.loan.interestRateAnnual",
  B90: "properties.tertiary.loan.monthlyRepayment",
  B93: "debts.other.balance",
  B94: "debts.other.interestRateAnnual",
  B95: "debts.other.monthlyRepayment",
  B100: "cashflowEvents.income.primary.name",
  B101: "cashflowEvents.income.primary.amount",
  B102: "cashflowEvents.income.primary.year",
  B105: "cashflowEvents.income.secondary.name",
  B106: "cashflowEvents.income.secondary.amount",
  B107: "cashflowEvents.income.secondary.year",
  B110: "cashflowEvents.income.tertiary.name",
  B111: "cashflowEvents.income.tertiary.amount",
  B112: "cashflowEvents.income.tertiary.year",
  B117: "cashflowEvents.expense.primary.name",
  B118: "cashflowEvents.expense.primary.amount",
  B119: "cashflowEvents.expense.primary.year",
  B122: "cashflowEvents.expense.secondary.name",
  B123: "cashflowEvents.expense.secondary.amount",
  B124: "cashflowEvents.expense.secondary.year",
  B127: "cashflowEvents.expense.tertiary.name",
  B128: "cashflowEvents.expense.tertiary.amount",
  B129: "cashflowEvents.expense.tertiary.year",
  B134: "planning.lifeExpectancyAge",
  B137: "spending.adjustments.pre65.deltaRate",
  B138: "spending.adjustments.age66To75.deltaRate",
  B139: "spending.adjustments.age76Plus.deltaRate",
  B141: "income.postRetirementSupplement.annual",
  B142: "income.postRetirementSupplement.startAge",
  B143: "income.postRetirementSupplement.endAge",
  B145: "assumptions.generalInflationRateAnnual",
  B147: "assumptions.propertyAppreciationRateAnnual",
  B149: "assumptions.cashYieldRateAnnual",
  B151: "assumptions.equityReturnRateAnnual",
  B153: "assumptions.salaryGrowthRateAnnual",
  B155: "assumptions.rentalIncomeGrowthRateAnnual",
  B157: "retirement.earlyPensionReductionPerYear",
  B159: "liquidity.minimumCashBuffer",
  B161: "liquidation.stockSellingCostRate",
  B163: "liquidation.propertyDisposalCostRate",
  B166: "properties.primary.liquidationPriority",
  B167: "properties.secondary.liquidationPriority",
  B168: "properties.tertiary.liquidationPriority"
} as const;

export type InputCell = keyof typeof CELL_TO_FIELD_ID;
export type FieldId = (typeof CELL_TO_FIELD_ID)[InputCell];

export const FIELD_ID_TO_CELL: Record<FieldId, InputCell> = Object.fromEntries(
  Object.entries(CELL_TO_FIELD_ID).map(([cell, fieldId]) => [fieldId, cell])
) as Record<FieldId, InputCell>;

export const ALL_INPUT_CELLS = Object.keys(CELL_TO_FIELD_ID) as InputCell[];
export const ALL_FIELD_IDS = Object.values(CELL_TO_FIELD_ID) as FieldId[];
