import { createEmptyFieldState } from "./inputSchema";
import { FieldState, ModelUiState } from "./types";

export const SAMPLE_DATA_EARLY_RETIREMENT_AGE = 49;
export const SAMPLE_DATA_PROJECTION_MONTH_OVERRIDE = 1;

export function createSampleDataFieldState(): FieldState {
  const fields = createEmptyFieldState();

  fields["profile.currentAge"] = 48;
  fields["income.employment.netAnnual"] = 80000;
  fields["assets.cash.totalBalance"] = 50000;
  fields["assets.equities.marketValue"] = 30000;
  fields["assets.equities.monthlyContribution"] = 350;
  fields["housing.01Residence.marketValue"] = 500000;
  fields["housing.01Residence.mortgage.balance"] = 50000;
  fields["housing.01Residence.mortgage.interestRateAnnual"] = 0.03;
  fields["housing.01Residence.mortgage.monthlyRepayment"] = 300;
  fields["retirement.statutoryAge"] = 65;
  fields["retirement.statePension.netAnnualAtStart"] = 16000;
  fields["spending.livingExpenses.annual"] = 50000;
  fields["dependents.01.displayName"] = "John";
  fields["dependents.01.annualCost"] = 2000;
  fields["dependents.01.supportYearsRemaining"] = 3;
  fields["dependents.02.displayName"] = "Jack";
  fields["dependents.02.annualCost"] = 1000;
  fields["dependents.02.supportYearsRemaining"] = 5;
  fields["dependents.03.displayName"] = "Bill";
  fields["dependents.03.annualCost"] = 4000;
  fields["dependents.03.supportYearsRemaining"] = 2;
  fields["dependents.04.displayName"] = "Stephen";
  fields["dependents.04.annualCost"] = 2500;
  fields["dependents.04.supportYearsRemaining"] = 3;
  fields["dependents.05.displayName"] = "Jane";
  fields["dependents.05.annualCost"] = 2860;
  fields["dependents.05.supportYearsRemaining"] = 6;
  fields["properties.01.displayName"] = "Sliema";
  fields["properties.01.marketValue"] = 300000;
  fields["properties.01.annualOperatingCost"] = 5000;
  fields["properties.02.displayName"] = "Gzira";
  fields["properties.02.marketValue"] = 150000;
  fields["properties.02.annualOperatingCost"] = 2000;
  fields["properties.03.displayName"] = "Qormi";
  fields["properties.03.marketValue"] = 220000;
  fields["properties.03.annualOperatingCost"] = 1200;
  fields["properties.04.displayName"] = "Gudja";
  fields["properties.04.marketValue"] = 80000;
  fields["properties.04.annualOperatingCost"] = 1000;
  fields["properties.05.displayName"] = "Marsa";
  fields["properties.05.marketValue"] = 120000;
  fields["properties.05.annualOperatingCost"] = 800;
  fields["assetsOfValue.01.displayName"] = "Jewelry";
  fields["assetsOfValue.01.marketValue"] = 50000;
  fields["assetsOfValue.01.appreciationRateAnnual"] = 0.02;
  fields["assetsOfValue.02.displayName"] = "Car";
  fields["assetsOfValue.02.marketValue"] = 40000;
  fields["assetsOfValue.02.appreciationRateAnnual"] = -0.05;
  fields["assetsOfValue.03.displayName"] = "Painting";
  fields["assetsOfValue.03.marketValue"] = 20000;
  fields["assetsOfValue.03.appreciationRateAnnual"] = 0.03;
  fields["assetsOfValue.04.displayName"] = "Boat";
  fields["assetsOfValue.04.marketValue"] = 180000;
  fields["assetsOfValue.04.appreciationRateAnnual"] = -0.05;
  fields["assetsOfValue.05.displayName"] = "Antiques";
  fields["assetsOfValue.05.marketValue"] = 82000;
  fields["assetsOfValue.05.appreciationRateAnnual"] = 0.02;
  fields["properties.01.rentalIncomeNetAnnual"] = 12000;
  fields["properties.02.rentalIncomeNetAnnual"] = 10000;
  fields["properties.03.rentalIncomeNetAnnual"] = 8000;
  fields["properties.04.rentalIncomeNetAnnual"] = 5000;
  fields["properties.05.rentalIncomeNetAnnual"] = 6500;
  fields["income.otherWork.netAnnual"] = 2000;
  fields["income.otherWork.endAge"] = 58;
  fields["debts.creditCards.balance"] = 1000;
  fields["properties.01.loan.balance"] = 50000;
  fields["properties.01.loan.interestRateAnnual"] = 0.03;
  fields["properties.01.loan.monthlyRepayment"] = 500;
  fields["properties.02.loan.balance"] = 8500;
  fields["properties.02.loan.interestRateAnnual"] = 0.02;
  fields["properties.02.loan.monthlyRepayment"] = 200;
  fields["properties.03.loan.balance"] = 15000;
  fields["properties.03.loan.interestRateAnnual"] = 0.05;
  fields["properties.03.loan.monthlyRepayment"] = 250;
  fields["properties.04.loan.balance"] = 4680;
  fields["properties.04.loan.interestRateAnnual"] = 0.02;
  fields["properties.04.loan.monthlyRepayment"] = 80;
  fields["properties.05.loan.balance"] = 9524;
  fields["properties.05.loan.interestRateAnnual"] = 0.03;
  fields["properties.05.loan.monthlyRepayment"] = 120;
  fields["assetsOfValue.01.loan.balance"] = 2500;
  fields["assetsOfValue.01.loan.interestRateAnnual"] = 0.03;
  fields["assetsOfValue.01.loan.monthlyRepayment"] = 75;
  fields["assetsOfValue.02.loan.balance"] = 6000;
  fields["assetsOfValue.02.loan.interestRateAnnual"] = 0.02;
  fields["assetsOfValue.02.loan.monthlyRepayment"] = 86;
  fields["assetsOfValue.03.loan.balance"] = 7500;
  fields["assetsOfValue.03.loan.interestRateAnnual"] = 0.05;
  fields["assetsOfValue.03.loan.monthlyRepayment"] = 125;
  fields["assetsOfValue.04.loan.balance"] = 40000;
  fields["assetsOfValue.04.loan.interestRateAnnual"] = 0.06;
  fields["assetsOfValue.04.loan.monthlyRepayment"] = 624;
  fields["assetsOfValue.05.loan.balance"] = 3800;
  fields["assetsOfValue.05.loan.interestRateAnnual"] = 0.03;
  fields["assetsOfValue.05.loan.monthlyRepayment"] = 110;
  fields["debts.other.balance"] = 4000;
  fields["debts.other.interestRateAnnual"] = 0.06;
  fields["debts.other.monthlyRepayment"] = 50;
  fields["cashflowEvents.income.01.name"] = "Inheritance";
  fields["cashflowEvents.income.01.amount"] = 50000;
  fields["cashflowEvents.income.01.year"] = 2035;
  fields["cashflowEvents.income.02.name"] = "Sell Painting";
  fields["cashflowEvents.income.02.amount"] = 10000;
  fields["cashflowEvents.income.02.year"] = 2029;
  fields["cashflowEvents.income.03.name"] = "Sell Jewels";
  fields["cashflowEvents.income.03.amount"] = 5000;
  fields["cashflowEvents.income.03.year"] = 2032;
  fields["cashflowEvents.expense.01.name"] = "Wedding";
  fields["cashflowEvents.expense.01.amount"] = 40000;
  fields["cashflowEvents.expense.01.year"] = 2036;
  fields["cashflowEvents.expense.02.name"] = "New Car";
  fields["cashflowEvents.expense.02.amount"] = 35000;
  fields["cashflowEvents.expense.02.year"] = 2029;
  fields["cashflowEvents.expense.03.name"] = "New AC";
  fields["cashflowEvents.expense.03.amount"] = 15000;
  fields["cashflowEvents.expense.03.year"] = 2034;
  fields["housing.downsize.year"] = 2030;
  fields["housing.downsize.newHomeMode"] = "Buy";
  fields["housing.downsize.newHomePurchaseCost"] = 250000;
  fields["stockMarketCrashes.01.year"] = 2027;
  fields["stockMarketCrashes.01.dropPercentage"] = 0.15;
  fields["stockMarketCrashes.01.recoveryYears"] = 1;
  fields["stockMarketCrashes.02.year"] = 2032;
  fields["stockMarketCrashes.02.dropPercentage"] = 0.2;
  fields["stockMarketCrashes.02.recoveryYears"] = 3;
  fields["stockMarketCrashes.03.year"] = 2037;
  fields["stockMarketCrashes.03.dropPercentage"] = 0.08;
  fields["stockMarketCrashes.03.recoveryYears"] = 3;
  fields["stockMarketCrashes.04.year"] = 2045;
  fields["stockMarketCrashes.04.dropPercentage"] = 0.18;
  fields["stockMarketCrashes.04.recoveryYears"] = 2;
  fields["stockMarketCrashes.05.year"] = 2050;
  fields["stockMarketCrashes.05.dropPercentage"] = 0.28;
  fields["stockMarketCrashes.05.recoveryYears"] = 6;
  fields["planning.lifeExpectancyAge"] = 85;
  fields["spending.adjustments.firstBracket.deltaRate"] = 0;
  fields["spending.adjustments.secondBracket.deltaRate"] = -0.1;
  fields["spending.adjustments.finalBracket.deltaRate"] = -0.2;
  fields["income.postRetirementSupplement.annual"] = 12000;
  fields["income.postRetirementSupplement.startAge"] = 58;
  fields["income.postRetirementSupplement.endAge"] = 69;
  fields["assumptions.generalInflationRateAnnual"] = 0.025;
  fields["assumptions.propertyAppreciationRateAnnual"] = 0.03;
  fields["assumptions.cashYieldRateAnnual"] = 0.025;
  fields["assumptions.equityReturnRateAnnual"] = 0.08;
  fields["assumptions.salaryGrowthRateAnnual"] = 0.03;
  fields["assumptions.rentalIncomeGrowthRateAnnual"] = 0.03;
  fields["retirement.earlyPensionReductionPerYear"] = 300;
  fields["liquidity.minimumCashBuffer"] = 50000;
  fields["planning.legacyAmount"] = 1000000;
  fields["liquidation.stockSellingCostRate"] = 0.05;
  fields["liquidation.propertyDisposalCostRate"] = 0.15;
  fields["liquidation.otherAssetDisposalCostRate"] = 0.02;
  fields["properties.01.liquidationPriority"] = 10;
  fields["properties.02.liquidationPriority"] = 7;
  fields["properties.03.liquidationPriority"] = 9;
  fields["properties.04.liquidationPriority"] = 4;
  fields["properties.05.liquidationPriority"] = 6;
  fields["assetsOfValue.01.liquidationPriority"] = 3;
  fields["assetsOfValue.02.liquidationPriority"] = 2;
  fields["assetsOfValue.03.liquidationPriority"] = 1;
  fields["assetsOfValue.04.liquidationPriority"] = 8;
  fields["assetsOfValue.05.liquidationPriority"] = 5;

  return fields;
}

export function createSampleDataUiState(): ModelUiState {
  return {
    majorFutureEventsOpen: true,
    advancedAssumptionsOpen: true,
    earlyRetirementAge: SAMPLE_DATA_EARLY_RETIREMENT_AGE,
    manualPropertyLiquidationOrder: false,
    projectionMonthOverride: SAMPLE_DATA_PROJECTION_MONTH_OVERRIDE
  };
}
