import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { GOLDEN_PERSONAS } from "./fixtures";
import {
  createGoldenPersonaSnapshot,
  GOLDEN_REFERENCE_DATE_ISO,
  GoldenSnapshotRecord
} from "./shared";

function buildSnapshotRecord(): GoldenSnapshotRecord {
  return Object.fromEntries(
    GOLDEN_PERSONAS.map((persona) => [persona.name, createGoldenPersonaSnapshot(persona)])
  );
}

function buildSnapshotSource(record: GoldenSnapshotRecord): string {
  return `import type { GoldenSnapshotRecord } from "./shared";

// Auto-generated by specs/runtime/golden/updateSnapshots.ts
// Reference date: ${GOLDEN_REFERENCE_DATE_ISO}
export const GOLDEN_SNAPSHOTS = ${JSON.stringify(record, null, 2)} satisfies GoldenSnapshotRecord;
`;
}

const here = dirname(fileURLToPath(import.meta.url));
const outputPath = join(here, "goldenSnapshots.ts");

console.warn("Updating snapshots — review the diff and commit them alongside the logic change that caused them.");
const record = buildSnapshotRecord();
writeFileSync(outputPath, buildSnapshotSource(record));
console.log(`Wrote ${outputPath}`);
